cnpem/epics-in-docker

Dockerfile, README.md
This is necessary for IOCs whose builds require additional tools, or for IOCs which require additional tools at runtime.
Since the build stage doesn't install any packages, we need to run "apt install" conditionally. For the final stage, we can simply add it to the existing install command. The variable expansion for both of the new variables isn't quoted, which is necessary to allow it to expand to a list of packages.
@mmdonatti
=> ioc: install user specified build and runtime packages.

Dockerfile, base/Dockerfile
This makes using iocsh much more practical, which is necessary when debugging applications. This means we have to install libreadline in the final container so the IOCs can be launched.
=> Build epics-base with readline support.

README.md, base/Dockerfile, base/install_area_detector.sh
I've included `libtiff` in the build so that we can use [`NDFileTIFF`](https://areadetector.github.io/master/ADCore/NDFileTIFF.html) plugin.
I've mistakenly left it off from #7.
=> base: include libtiff in areaDetector build

.github/workflows/base-image.yml, base/docker-compose.yml
I've changed the CI so that it works on forked repositories by using GItHub context variables. Although there are more build environment variables now, we can still build the image locally only defining the `TAG` (and `JOBS`) variables.
I've also fixed the issue of having tag pushes ignored. It works now. I've already tested in my fork. However, I'm not sure if you would like to keep with the idea of having any tag triggering the CI.
=> Fix CI workflow for forked repositories

Dockerfile
The .git directory for submodules isn't being removed by this command, but we will assume those are smaller, so not worth the effort to remove cleanly.
=> ioc: remove .git directory during build.

Dockerfile
This allows us to run an IOC which was built along with its support module. This pattern is used for some community modules, including motor's and areaDetector's ones.
A new (empty) stage has been created only to specify the base image in the COPY command, since `--from` argument [does not support variable expansion][1].
`build-stage` has been moved below `no-build` stage, so bad multi-stage resolvers won't fail for the new stage.
[1]: https://forums.docker.com/t/how-can-i-expand-a-variable-within-a-copy-command-in-the-dockerfile/113538/2
=> ioc: add stage without IOC building.

Dockerfile, base/Dockerfile, base/install_epics.sh, base/install_modules.sh, base/lnls-get-n-unpack.sh
Installing through tarballs is useful to enable us to include software that is not yet packaged in the distribution repositories.
A custom extraction script is interesting to solve, in a centralized way, permission issues in rootless container engines both for source code and binaries packages.
I've named the custom script `untar`, but I'm open to suggestions for other names.
=> Install tarball packages with custom extraction

Dockerfile
This is required to use `BUILD_PACKAGES` to install any package. No recommended package option has also been enabled to avoid unused packages in the resulting IOC image. Lines have been broken to make it easier to read and maintain this step.
=> ioc: use non-interactive install for build-stage.

Dockerfile, README.md, base/Dockerfile, base/lnls-run.sh
Setting this script as the default entrypoint for our containers allows IOCs which use "st.cmd" as their startup script to be launched without specifying any command in the command line or YAML orchestrator file, and still support other startup scripts or shell wrappers that perform the necessary setup before launching the IOC, but not having to call procServ themselves.
Furthermore, it means that there is a default location for the procServ socket, which can be documented.
=> ioc: add script to launch IOCs inside container.

base/Dockerfile, base/install-functions.sh, base/install_area_detector.sh, base/install_epics.sh, base/install_modules.sh, base/install_motor.sh
These installation functions can be used in other scripts. This simplifies their logic through reuse and centralizes standardization. I've also refactored `install_epics.sh` to use it already.
The name of the script is something I'm open to suggestions. I'm okay with the name, but I'm sure there is a better one that I couldn't know of. :)
=> base: extract install functions to shared file.

Dockerfile
This has been missing from the latest release (v0.4.0), and I don't have the rights to push directly to the main branch.
=> Post-release development version bump.

.github/workflows/base-image.yml
This allows us to avoid writing our own commands for things, and works with GHA cache for images, which speeds up CI and avoids unnecessary resource usage.
=> ci: use docker/bake-action.

base/Dockerfile, base/backport-adsupport-nanohttp.patch, base/install_area_detector.sh
We now use the merged version of the patch and follow the backport filename convention to make it explicit it can be removed when failing to be applied.
To follow how other patches are applied, the `patch` utility is used instead of git-apply.
=> base: use the accepted patch for nanohttp_stream.

CHANGES.md, base/install-functions.sh, base/install_area_detector.sh, base/install_modules.sh, base/install_motor.sh
Right after being installed, a module adds its own path to the RELEASE file. Use this as the source of truth for specifying the dependencies' path in later module builds. Since a module cannot be built without its dependency already built, this does not limit our installation scripts.
This removes duplication of several paths of modules, which may now change more easily.
=> base: use RELEASE to determine module paths.

.github/workflows/ioc-images.yml, CHANGES.md, README.md
Based on testing done for https://github.com/lnls-dig/rffe-epics-ioc/pull/11
=> ci: add reusable job for IOC images.

README.md
The version in a "uses" key is mandatory.
Fixes: 7b01e955aa7bd2732bb8ef53c24efad9d6347aaa
=> README: fix GitHub Actions job definition.

.github/workflows/ioc-images.yml
GitHub context variable `ref_name` has an invalid pattern (`<pr>/merge`) for container image tags when events are generated by pull requests. In such cases, `head_ref` should be used in the IOC build workflow instead.
Fixes: 4cd3893 ("ci: add reusable job for IOC images.")
=> ci: use valid tag name for pull request events.

CHANGES.md, base/Dockerfile, base/caputlog-waveform-fix.patch, base/install_modules.sh, base/musl/Dockerfile
This fixes interaction with waveform PVs when the same channel is used for putting and for monitors, as we reported in tech-talk [1].
[1] https://epics.anl.gov/tech-talk/2024/msg00481.php
=> base: add caPutLog patch for waveforms.

.github/workflows/included-images.yml, CHANGES.md, README.md, images/docker-compose-opcua.yml
Since the OPCUA IOC we use is built alongside the OPCUA module, we can simply export the IOC image ourselves.
---
This is still missing automatic generation of the image in CI. Creating the tagged image is easy, we just need to [depend](https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions) on the workflow which pushes the base image. The hard part is running it for PRs as well... This means it probably has to be in the same workflow and must deal with the recently built base image which will have its own name but should be called `X.Y.Z-dev`.
I'm not sure how far we need to go before merging and tagging a release so it can be used.
=> images: add OPCUA image.

Dockerfile
Modern EPICS templates defines an optional include to a `.local` version of the configuration files. However, it is not guaranteed that this haven't been removed in the IOC, or that another template was used, which does not contain this logic. In such situations, compiling will succeed if we place STATIC_BUILD in the local file, but the IOC won't be statically linked, as the configuration won't ever be loaded.
Use CONFIG_SITE directly to avoid mistakenly compiling an application with dynamic linking when the used target is `static-link` and the template does not include local settings. This also lowers the knowledge required about the EPICS build system to successfully build the IOCs.
Note that appending to the end of CONFIG_SITE will correctly override any configuration in …
=> ioc: configure static link directly on CONFIG_SITE.

CHANGES.md, base/install_modules.sh
By making Calc depend on Sequencer, all IOCs which directly or indirectly depend on Calc must explicitly link against Sequencer library when using static-link target. This means most previously dynamic-linked IOCs will not cleanly build without changes to src/Makefile when moving to epics-in-docker. In turn, we gain the [feature of editing sseq records at runtime][1], which is not used by IOCs we currently maintain and is probable not to be used by future ones.
Drop support for editSseq in favor of making it easier to containerize new IOCs.
This reverts commit https://github.com/cnpem/epics-in-docker/commit/a2096baee404ce724eb0cf91eda57d98fce059b7.
[1]: https://github.com/epics-modules/calc/blob/R3-7-5/calcApp/src/calcSupport_withSNCSEQ.dbd
=> base: remove CALC dependency on Sequencer

base/install_modules.sh
Using with multiple processes breaks the build, as inter-dependencies are not properly handled when generating the substituted databases. Use a single process for this specific module, so that local builds of other modules can use multiple jobs without breaking.
=> base: use single job to build ipmiComm.

Dockerfile, README.md, base/lnls-get-n-unpack.sh
Make all busybox goodies available in the PATH without having to worry about them being from busybox. This is done automatically for Alpine, but not for Debian.
This removes the need to install wget, since it is already provided by busybox. However, its version packaged by Debian does not implement `-o` flag, requiring us to use bash redirection instead.
Fixes: ffdbecc1 (ioc: initial commit.)
=> ioc: install busybox symbolic links.

CHANGES.md, Dockerfile, base/Dockerfile
APT is one of the applications that assume multiple effective UIDs exist, so that it can sandbox itself. When running with `ignore_chown_errors` option enabled (see [podman(1)](https://manpages.debian.org/bookworm/podman/podman.1.en.html#Rootless_mode)), this will lead to `setgroups`, `seteuid` and `setguid` syscalls to fail, breaking most of `apt` commands.
Ensure that a single UID is used inside the containers, both at base build image (without `/etc/set{u,g}id` settings) and IOC runtime, especially allowing one to properly use apt.
=> Ensure single UID is used inside containers

base/install_area_detector.sh, base/install_motor.sh
These commits have been extracted from #59 to be merged earlier.
=> Remove Git repositories from base images

.github/workflows/base-image.yml, CHANGES.md, Dockerfile, README.md, base/Dockerfile, base/docker-compose.yml, images/docker-compose-opcua.yml
And update relevant package versions.
=> base: update to Debian 12.

Dockerfile
Since Debian 12, installing packages [outside a virtual environment is an error by default][1] as first specified by [PEP 668][2]. The rationale for forcing this is not applicable in our context, since the container image is dedicated to the IOC under construction, which renders it an isolated environment of its own.
Users should still provide RUNTIME_PIP_PACKAGES that are compatible with the system packages, not really breaking the system, similarly to what is done for shared libraries.
[1]: https://salsa.debian.org/python-team/packages/python-pip/-/commit/5aeba2464e36020a34e2bc074872771f5ef4973d
[2]: https://peps.python.org/pep-0668
Fixes: 39bb0d4e1d42 (base: update to Debian 12., 2024-10-31)
=> ioc: allow pip to install packages system-wide.

CHANGES.md, Dockerfile, README.md, base/Dockerfile, base/install_area_detector.sh, base/install_modules.sh, base/lnls-prune-artifacts.sh, images/docker-compose-mca.yml, images/docker-compose-motorpigcs2.yml, images/docker-compose-opcua.yml, images/docker-compose-pvagw.yml
Both `dynamic-link` and `no-build` targets generate unnecessarily large IOC images due to the trivial `COPY` done from `/opt`. Clean up everything from there and `/usr/local` directory before doing the `COPY` to the IOC image.
Clean up strategy proposed here is the following:
- Remove entirely any module that does not have a shared library linked against binaries under the IOC target directories (i.e. `/opt/$REPONAME` or `$RUNDIR`);
- Prune directories from used modules and EPICS base not containing shared libraries, EPICS databases or autosave requirement files;
- Remove any shared library not linked against binaries under IOC target directories;
- Remove all statically linked libraries;
For pruning module directories, another approach that could be followed is to delegate this …
=> Prune unused artifacts from non-static builds

base/install_modules.sh
Using a subdirectory of the tarball as the module's location means the tarball's root, recsync/, isn't included in the $EPICS_RELEASE_FILE and can't be used for image pruning steps. This means that, for IOCs which don't use reccaster, the recsync/ directory is still present in the final image; and even for those which use reccaster, the files in the directory haven't been pruned (though they only amount to 288K).
In order to guarantee that the recsync/ directory is always removed when unused, we extract the reccaster module from it, and remove all other files.
---
Fixes #102
=> base: don't use recsync/client for RECCASTER.

RELEASE.md
Updating the 'release' branch manually is no longer necessary after b1163e1 (ci: add workflow to update the release branch., 2024-11-08).
=> RELEASE: remove manual update of release branch.

Dockerfile, base/Dockerfile, base/lnls-build-ioc.sh
The .git directory is removed mainly for reducing the size of the resulting IOC image. However, doing this before compiling the IOC rules out the possibility of automatically detecting the version during the build (e.g. by calling `git describe` in the Makefile). Defer the removal to right after the IOC has been built, but still before it is COPY'ed to the final image, satisfying both goals.
The downside of this approach is the duplication in both dynamic and static build stages, which need to be kept in sync. Given that a similar issue already occurs for the build pipeline itself and that the benefits outweigh the drawbacks, it seems fine by now.
=> ioc: defer git directory removal until after build.

base/lnls-build-ioc.sh
When the code was extracted to a standalone script in the fixed commit, undefined variables have been enforced not to exist by using the `-u` switch. However, SKIP_TESTS is thought to be optionally defined in the compose file (in order to make it more concise), which means it is often undefined. Give it the default value of false to make it optional again. Keep the setting of failing upon usage of undefined variables, as it is still beneficial in general.
Notice that no other variable needs a default value, as we enforced RUNDIR to be defined (because it is argument of a required option), and JOBS always had a default value.
Fixes: 1ed359f (ioc: deduplicate build steps in different targets., 2025-05-22)
=> ioc: default SKIP_TESTS to false.
